### ISSUE TITLE
Listgroup, select

### ISSUE THREAD

**Issue by mitchellklijs** [rickardn/listgroup.js#5]
If you use the bootstrap listgroup component directly, is there still a way to keep track of what option is selected using the plugin?

**Comment by mitchellklijs** [comment]
Is that possible?

I would want to achieve a list group with an image inside of it.

**Comment by rickardn** [comment]
The plugin doesn't expose any APIs to get the selected items (yet), however it is very easy to do with jQuery.
    `$('#mylistgroup .active')` will select the active items.

What kind of API did you have in mind?

**Comment by samcov** [comment]
It's likely as simple as being able to set the href so that an event can be spawned to perform some action, like execute some javascript. Looking at what's active isn't a realistic solution to events!

An API would also include add, remove, etc. While you copy the select data, you fail to handle the onchange event, which would be the logical thing to move to the href, using href="javascript:someFunction()".

However, the safest thing to do is to have a setter for the href.

BTW, I would be remiss if I didn't say that this is a sweet little plugin, good work!

**Comment by samcov** [comment]
Ok, I tested it a bit, and you'll have to change the href attribute to javascript:void(0), then move the onchange event to onclick.

I changed the code to this and while it works, I'm not sure you want to do it this way, a setter for events may be the better way to go, but you'll likely know better. 
    var href='#'; // default value
    var onclick=''; // default value
        if ($select.attr('onchange'))
    {
        href = "javascript:void(0)";
        onclick = "javascript:"+$select.attr('onchange');
    }

```
    $select.find('option').each(function (i, item) {
        var $item = $(item);

        var $new = $('<a>')
                    .attr('href', href)
                    .attr('onclick', onclick)
                    .addClass('list-group-item')
                    .attr('data-value', $item.val())
                    .text($item.text());
```

**Comment by samcov** [comment]
I just noticed that you already have a click event added that also attempts to look for clicks on the select's options, so I'm not sure of the best way to do this, I defer to your better knowledge!

**Comment by watherton** [comment]
Hi, @samcov, did you manage to figure out how to get the selected value. Basically, I want to use it to populate a comments box, with pre-determined values.

**Comment by rickardn** [comment]
If you have multiselect you can do '$('#mylistgroup .active')' which returns a list of selected items, and then inspect the .text() for each item. Otherwise you do the same thing but the list contains only one item.
